### ISSUE TITLE
"Restore Previous Session" feature doesn't work

### ISSUE THREAD

**Issue by Antonius32** [MoonchildProductions/Tycho#124] opened 2016-08-29 13:09 UTC
The "Restore Previous Session" feature currently doesn't work; the menu item in the various History menus is always grayed out (see attachment below).

![restore-previous-session](https://cloud.githubusercontent.com/assets/9977071/18051995/2aea8134-6df8-11e6-9cfd-bff1c2881afe.png)

If I click the menu item anyway, the Error Console does _not_ register any errors.

**Comment by janekptacijarabaci** [comment] 2016-08-29 13:45
See also https://github.com/MoonchildProductions/Tycho/blob/Tycho_alpha2/browser/base/content/browser.js#L1067

**Comment by wsdfhjxc** [comment] 2016-08-29 19:46
According to DOM Inspector the `Browser:RestoreLastSession` command element always gets `disabled` property set to `true` and the menu item linked with this command follows this property which results in being greyed-out all the time. Removing this property from command element (or setting it to `false`) causes unlocking the menu item.

Maybe the problem is with [this method call](https://github.com/MoonchildProductions/Tycho/blob/db7d338053c68af15e083e2c2badabe4e7b379b8/browser/base/content/browser.js#L1069) not being executed at all?

**Comment by janekptacijarabaci** [comment] 2016-08-29 20:09
See also https://bugzilla.mozilla.org/show_bug.cgi?id=898308

**Comment by wolfbeast** [comment] 2016-08-29 23:06
Blocks #22

**Comment by wsdfhjxc** [comment] 2016-08-30 21:01
I couldn't find explicit differences between Tycho's and current PM's sources regarding this command and session initialization, yet in current PM it works correctly. But I've found that it can be fixed in Tycho by refreshing the command's accessibility directly before displaying the menu. I'm not sure if this is an eligible way of fixing such strangely broken things, so I didn't make a PR for the moment.

**Comment by wolfbeast** [comment] 2016-08-30 23:18
The difference between the calls is that `ss.init()` in PM26 is synchronous, and in the re-base it's been made asynchronous. So, `ss.init()` is likely not going to be completed before the check is made in the next line of the window opening code. We'll have to change the browser window startup code to async as well to have the check be performed in a callback/promise when `init()` is done, and not before.

This will need the /browser parts of BMO bugs 881049 and 898308

**Comment by Antonius32** [comment] 2016-08-31 09:09
> This will need the /browser parts of BMO bugs 881049 and 898308

Uhm, all changes made in bugs 881049 and 898308 are in the /browser subtree, or am I missing something? In other words, do we need all parts of the aforemontioned bugs?

**Closed** 2016-09-07 17:27 UTC
